[package]
name = "two_sum"
version = "0.1.0"
edition = "2021"
description = "leetcode.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
